### ISSUE TITLE
Conflict with api-platform/core ^2.6 blocks installation with Sylius 1.10

### ISSUE THREAD

**Issue by Geolim4** [umanit/sylius-product-variant-attribute-plugin#4]
Hello,

In the latest release (1.9.0) of the bundle [you defined a conflict](https://github.com/umanit/sylius-product-variant-attribute-plugin/commit/69a95222666c1773fa9f4751a3c856841121945b#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R13) with `api-platform/core ^2.6`.

However, Sylius 1.10  requires `api-platform/core ^2.6`, thus blocking the package installation.

I assume you defined on purpose the bundle not to be compatible with Sylius 1.10 but only 1.9 ?

Thank you :)

**Comment by DjLeChuck** [comment]
Hi,

This conflict was added by @swan-andre : https://github.com/umanit/sylius-product-variant-attribute-plugin/pull/3/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R12-R13

I think it's because it's also in the Sylius 1.9 [composer.json file](https://github.com/Sylius/Sylius/blob/1.9/composer.json#L163).

I can make a new tag for `1.10`  without this constraint, but we should test if the plugin works out of the box!

**Comment by Geolim4** [comment]
> I can make a new tag for `1.10` without this constraint, but we should test if the plugin works out of the box!

Indeed, it would be great, the changes from 1.9 to 1.10 are here: https://sylius.com/blog/new-release-sylius-v1-10/

Something inside that release that may incompatible with bundle v1.9 ?

**Comment by DjLeChuck** [comment]
I don't know, things to check are Sylius templates and JS on the products attributes.

I will test this tonight. :)

**Comment by Geolim4** [comment]
> I don't know, things to check are Sylius templates and JS on the products attributes.
> 
> I will test this tonight. :)

Okay thanks, I'll buy you a beer on Nantes some day :)

**Comment by DjLeChuck** [comment]
Done: https://github.com/umanit/sylius-product-variant-attribute-plugin/releases/tag/1.10.0 👍🏻

**Comment by Geolim4** [comment]
Thank you @DjLeChuck ❤️

**Comment by Geolim4** [comment]
@DjLeChuck send me an email at contact[at]geolim4.com so we can take a beer around some day :)
